### ISSUE TITLE
AppVeyor failure

### ISSUE THREAD

**Issue by joshgo** [phatcher/CsvReader#16]
AppVeyor seems to be not configured completely. It does not have the nunit binaries, therefore it can't run the test and detect some of the NUnit related classes. Even though AppVeyor is failing, the project is actually fine because all the unit tests are passing when you run it via nunit-console / gui.

Possible fixes are:

1. add a "nuget restore" call in AppVeyor
2. call the supplied build scripts (**)

**I have used the build scripts on my machine, and they work fine. I have not had a chance to try in appveyor and verify they work there too.

**Comment by phatcher** [comment]
Added the "nugget restore" to the pre-build step, also updated the readme to show the nuget version and build status
