### ISSUE TITLE
LumenWorksCsvReader.3.9.1. not compatible with Net Core 1.1

### ISSUE THREAD

**Issue by renatobarbato** [phatcher/CsvReader#35]
Hi,
I have this issue:

error: Package LumenWorksCsvReader 3.9.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package LumenWorksCsvReader 3.9.1 supports: net20 (.NETFramework,Version=v2.0)

**Comment by gehnster** [comment]
I'm also having this issue.

**Comment by eman1986** [comment]
Same here, be nice to add Core support

**Comment by phatcher** [comment]
When I looked at it a few months ago it was tough as some of the API's hadn't been ported yet.

I'll take a look in March once VS 2017 is out - I can also accept a pull request if anyone wants to do the work.

The other question is whether it deserves a re-write if we have to port it to .NET Core.

**Comment by gehnster** [comment]
I took a look at it. I created a .NET Standard PCL and moved the code over to it. Looks like System.Data and System.ComponentModel aren't complete yet and won't be included until .NET Standard 2.0 comes out. Unfortunately .NET Standard 2.0 won't be released until Q4 2017.

**Comment by phatcher** [comment]
@gehnster That's the sort of thing I found out a while ago - when they decided not to include the generic ADO schema stuff it makes doing this sort of this quite tough.

As I was wondering, is it worthwhile doing a re-write to clean up the concepts etc and then limit the feature-set that's exposed by the .NET Core version?

**Comment by gehnster** [comment]
I personally use it in a very basic way. The csv files I'm reading are no more then a couple dozen records and its not used often.

**Comment by IGx89** [comment]
BTW, looks like someone's submitted a PR to convert it to .NET Standard 2.0: https://github.com/phatcher/CsvReader/pull/45

I'm using the existing version in a  .NET Core 2.0 project myself as-is, though VS gives me a warning. Having a proper .NET Standard 2.0 bundle would be ideal.

**Comment by bradleypatton** [comment]
Any update on this? Looks like there might be a PR to support .net standard 2.0 but there was a build failure?

**Comment by yotewach** [comment]
I waiting to this support

**Comment by phatcher** [comment]
I've updated the solution/projects to support netstandard2.0 but there are still some build issues - does build/test in VS2017 though

**Comment by phatcher** [comment]
@bradleypatton @yotewach @renatobarbato @gehnster @eman1986 @IGx89 

I've update the projects to VS2017 and it now supports net20->461 and netstandard1.3, netstandard2.0 can check and see if there's anything missing before I push the 4.0 release

**Comment by bazer** [comment]
Any news on the new release? We are also migrating to .net standard 2.0 and it would be nice to be able to use the nuget package without build warnings. I can try and help if there is something that needs fixing to get it out there.

**Comment by phatcher** [comment]
@bazer I'll be pushing a V4 which will be netstandard 2.0 compliant in the next couple of days - unfortunately the day job has got in the way :-)

**Comment by bazer** [comment]
@phatcher Cool, thanks!

**Comment by phatcher** [comment]
@renatobarbato, @bazer @bradleypatton @gehnster @eman1986 @IGx89 
I've just released 4.0 which supports netstandard 1.3 and 2.0.
Please file any problems as new issues

**Comment by bazer** [comment]
Thanks, will test it out!
