### ISSUE TITLE
Index out of bound when reading TSV w/o header

### ISSUE THREAD

**Issue by INRIX-Mark-Gershaft** [phatcher/CsvReader#38]
Problem seems to lie in the fact that Columns list is initialized to an empty list, but in object FieldValue(int i) it is checked to be not null and not checked to be an empty list causing an attempt to use Columns list for data conversion and failure to find column since list is empty.

Sample code:

                using (var streamReader = new StreamReader(_sourceBcpFilePath))
                {
                    using (var bcpReader = new CsvReader(streamReader, false, _delimiter, _quote, _escape, _comment, ValueTrimmingOptions.All))
                    {
. . .
bcpReader.GetValue(0);
. . .
                    }
                }

**Comment by joshgo** [comment]
You should submit a unit test that shows this error.

**Comment by INRIX-Mark-Gershaft** [comment]
Fixed by https://github.com/phatcher/CsvReader/commit/6e255008f730a67448801c47dae6145dd02f8bc9#diff-0d66ae192d7d3c3db093c6b8df11677b

**Comment by INRIX-Mark-Gershaft** [comment]
Suggested unit-test:
using (var reader = new StringReader("1,1,2,Hello\r\n3,3,4,World"))
            {
                using (var csvReader = new CsvReader(reader, false, '\t', '\0', '\0', '#', ValueTrimmingOptions.All))
                {
                    while (csvReader.ReadNextRecord())
                    {
                        for (int i = 0; i < csvReader.FieldCount; i++)
                        {
                            var record = (csvReader as IDataRecord);
                            record.GetValue(I);
                        }
                    }
                }
            }
