### ISSUE TITLE
Porting to .net portable

### ISSUE THREAD

**Issue by codehippie1** [phatcher/CsvReader#40]
I am a Xamarin developer. Would you be able to port this package to PCL?

This is the error I am getting, trying to add the nuget package to my PCL project

Error	 - Could not install package 'LumenWorksCsvReader 3.9.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by phatcher** [comment]
See #35 as it would likely be part of that - happy to take a pull request which produces a PCL version

I think it gets tricky due to the use of the ADO.NET schema bits

**Comment by phatcher** [comment]
@codehippie1 I've updated the project to support netstandard2.0 - is this sufficient for your use case?

**Comment by codehippie1** [comment]
Net standard is the way to go. Thank you @phatcher.
