### ISSUE TITLE
Does it support .NET Core 2.0

### ISSUE THREAD

**Issue by yotewach** [phatcher/CsvReader#48]
this library support dotnet core 2.0  or not ?

**Comment by phatcher** [comment]
Current code base does, though there are some issues with the build process that I'm trying to resolve

**Comment by phatcher** [comment]
@yotewach Code base now supports netstandard1.3 and netstandard2.0

**Comment by murdockcrc** [comment]
@phatcher : I guess the latest version available in the NuGet Gallery (3.9.1) does not support .netstd 2.0? Is there a plan to update the nuget package itself with the latest code?

**Comment by phatcher** [comment]
@murdockcrc Yes, I should get around to releasing a netstandard version this weekend

**Comment by phatcher** [comment]
@yotewach, @murdockcrc I've just released 4.0 which supports netstandard 1.3 and 2.0.
Please file any problems as new issues
