### ISSUE TITLE
Link out of date

### ISSUE THREAD

**Issue by Olivercomputing** [phatcher/CsvReader#5]
Minor issue (would have emailed but couldn't find an address) - the link to CsvReader in the description is to https://www.nuget.org/packages/CsvReader/, which is indicated as removed. A current one is evidently https://www.nuget.org/packages/LumenWorksCsvReader/. I assume it should point there.

**Comment by phatcher** [comment]
Thanks I'll update it

**Comment by phatcher** [comment]
Fixed
