### ISSUE TITLE
Start parsing at specific row

### ISSUE THREAD

**Issue by korneliuscode** [phatcher/CsvReader#51]
hi, I need the capability to start parsing at a specifc row, as some of the CSV files contain certain information on top that are not the column headers. Therefore I want to skip the first few rows (row number varies). Can this be included in the library or what woul be the best approach to this?

Thanks!

**Comment by phatcher** [comment]
@uwebraunholz I'd say it's not part of the library, as it's too context dependent.

My suggestion would be to open the stream yourself and then position it to where you need to start parsing the CSV and then pass that stream into a CsvReader; you will probably have to set up the headers yourself

Now if that doesn't work, then modifying one of the constructors so it does being a sensible approach.
