### ISSUE TITLE
Troubleshooting Column Limits in Bulk Copy

### ISSUE THREAD

**Issue by kirikintha** [phatcher/CsvReader#59]
Hello,

I have been using CSVReader successfully for two years now in a database import program I run, however I am running into an issue I need some help troubleshooting.

I have a CSV file I am importing from a third party with an obscene amount of columns. The current total column count in this file is 196. I realize this is an extreme edge case, but I cannot alter this file and the import is not optimal, but it's what I have to work with. 

Right now, I am easily importing 50-60 columns with no problem, but at about column 150 the import seems to break and throws a malformed exception. The file itself is clean, and is not malformed and I have verified in another program that I can get the data into the database without error.

I am thinking that this is a buffer issue (stream issue), but I am wondering if you have any hard limits on Column count? 

Also, do you have any advise for such an odd use-case, or troubleshooting for a large column and field set? This may also be relevant to other developers, so I wanted to post here.

Thank you for you work on this project!

**Comment by jakubmaguza** [comment]
Can you provide any test data? I create random data with 2000 columns and 2000 rows and there is no exception.

**Comment by kirikintha** [comment]
@jakubmaguza - I sure can, let me put together a sample. Thanks for the help!

**Comment by jakubmaguza** [comment]
@kirikintha Hi. Unfortunatelly the url is broken. Can you send it one more time?

**Comment by kirikintha** [comment]
@jakubmaguza - here is another attachment. Let's see how this goes. The columns have fairly long names in some places, and some eccentricity, but they are all quoted.

[Audit-Large Column List.txt](https://github.com/phatcher/CsvReader/files/2496387/Audit-Large.Column.List.txt)

**Comment by jakubmaguza** [comment]
I took a quick look at this file and it's braking at last row, where you don't have comma as last character.

**Comment by phatcher** [comment]
@kirikintha Looking at the sample test @jakubmaguza provided the issue is the parsing mode for the file.

By default the action on a missing field error is ParseError which means if you have a malformed line, the parser will throw an exception.

However you could set this to ReplaceByNull or ReplaceByEmpty, you may still have a issue with SQLBulkCopy as it is very particular about column types but this may be helped with the column default value setting.

I've added further tests around the MissingFieldAction into the code...

        [Test]
        public void MissingFieldNull()
        {
            using (var csv = new CsvReader(new StringReader("a,b,\nc,d"), false))
            {
                csv.SkipEmptyLines = true;
                csv.MissingFieldAction = MissingFieldAction.ReplaceByNull;

                RowCheck(csv, "a", "b", string.Empty);
                RowCheck(csv, "c", "d", null);

                Assert.That(csv.ReadNextRecord, Is.False);
            }
        }

        [Test]
        public void MissingFieldEmpty()
        {
            using (var csv = new CsvReader(new StringReader("a,b,\nc,d"), false))
            {
                csv.SkipEmptyLines = true;
                csv.MissingFieldAction = MissingFieldAction.ReplaceByEmpty;

                RowCheck(csv, "a", "b", string.Empty);
                RowCheck(csv, "c", "d", string.Empty);

                Assert.That(csv.ReadNextRecord, Is.False);
            }
        }

        [Test]
        public void MissingFieldException()
        {
            using (var csv = new CsvReader(new StringReader("a,b,\nc,d"), false))
            {
                csv.SkipEmptyLines = true;
                csv.MissingFieldAction = MissingFieldAction.ParseError;

                RowCheck(csv, "a", "b", string.Empty);
                RowCheck(csv, "c", "d");

                Assert.Throws<MissingFieldCsvException>(() => { var x = csv[2]; });
            }
        }

**Comment by kirikintha** [comment]
Hi everyone, thank you kindly for the update on how to handle the parse errors - I am working with the missing field exception examples and getting farther down the road. I also did an analysis on the file and it is malformed so I am having to go in and try some variation on the DDL and see if I can make it work.

Thank you so much for your help and analysis!
