### ISSUE TITLE
Replacement for FastCsvReader from its author

### ISSUE THREAD

**Issue by slorion** [phatcher/CsvReader#8]
Hello, I am the original author of FastCsvReader. It's been a long while since I wrote that library and I had a replacement which was on Codeplex that I recently put on github. Upon seeing your project, I thought it might interest you.

You can take a look at https://github.com/slorion/nlight for the library. The CSV reader is https://github.com/slorion/nlight/blob/master/src/NLight/IO/Text/DelimitedRecordReader.cs. You can go to https://github.com/slorion/nlight/tree/master/src/NLight.Tests.Unit/IO/Text to see it in action or https://github.com/slorion/nlight/tree/master/src/NLight.Tests.Benchmarks to benchmark it (including against my old reader).

I plan to release the library on nuget later this week, after adding some more unit tests.

p.s. My name is Sébastien Lorion, you misspelled it for "Sebastian Lorien" in a couple of places :)

**Comment by phatcher** [comment]
Sébastien
Thanks for the information - I'll check it out and fix up your name :-)
I'd also suggest posting this information against the original CodeProject article as it still gets traffic

**Comment by slorion** [comment]
I agree and I just posted an edit to the article pointing to this repository as well as my new library. Thank you again for taking the time to setup this repo.
